src/views.py
from datetime import date
from flask import Blueprint, render_template, flash, request, session, redirect
from models import db, Books, Borrows, Members
from forms import checkmember, AddBookForm, AddMemberForm, DeleteMemberForm, IssueBookForm, ReturnBookForm, SignUpForm, UserPageForm, SearchBookForm, DeleteBookForm, IssueLateForm
from sqlalchemy import and_, asc

app = Blueprint("app", __name__,template_folder='../templates')

@app.route('/')

@app.route('/user', methods=['GET','POST'])
def userpage():
    userpageform = UserPageForm(request.form)
    email = userpageform.email.data
    password = userpageform.password.data

    if request.method =='POST':
        
        if (email == '') | (password == ''):
            flash("Error! Missing Fields")
            return render_template('login.html')

        member = Members.query.filter(Members.email == email).first()

        if (member is not None) and (member.email == email) and (member.password == password):
            session['username'] = member.username
            return showbooks()

        else:
            flash("Error! Either Member email or Member password or both do not match")
            return render_template('login.html')

    elif 'username' not in session:
        return render_template('login.html')

    else:
        return showbooks()

@app.route('/index')
def index():
    return render_template('index.html')

@app.route('/signup', methods=['GET','POST'])
def signup():
    signupform = SignUpForm(request.form)
    username = signupform.username.data
    email = signupform.email.data
    password = signupform.password.data
    confirmpassword = signupform.confirmpassword.data

    if request.method =='POST':

        if (username == '') | (email == '') | (password == '') | (confirmpassword == ''):
            flash("Error! Missing Fields")
            return render_template('index.html')

        member = Members.query.filter(Members.email == email).first()

        if member is None:

            if password == confirmpassword:
                member = Members(username, password, email, cost = 0)
                db.session.add(member)
                db.session.commit()
                return render_template('login.html')

            else:
                flash("Error! Password and Confirm Password are different.")
                return redirect('index')

        else:
            flash('Error! User with the same email already exists.')
            return redirect('index')

    else:
        return redirect('index')

@app.route('/signout')
def signout():
    session.pop('username',None)
    return render_template('login.html')

@app.route('/add_member', methods=['GET','POST'])
def add_member():
    addmemberform = AddMemberForm(request.form)
    email = addmemberform.email.data
    username = addmemberform.username.data
    password = addmemberform.password.data

    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as Admin to access these functions")
        return render_template('login.html')
        
    if request.method == 'POST':

        if (username == '') | (email == '') | (password == ''):
            flash("Error! Missing Fields")
            return render_template('addmember.html', username = session['username'])

        member = Members.query.filter(Members.email == email).first()

        if member is None:
            member = Members(username, password, email, cost = 0)
            db.session.add(member)
            db.session.commit()
            flash("Successfully Added!")

        else:
            flash("Error! User with the same email already exists.")

    return render_template('addmember.html', username = session['username'])

@app.route('/delete_member', methods=['GET','POST'])
def delete_member():
    deletememberform = DeleteMemberForm(request.form)
    email = deletememberform.email.data

    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as Admin to access these functions")
        return render_template('login.html')
        
    if request.method == 'POST':

        if (email == ''):
            flash("Error! Missing Fields")
            return render_template('addmember.html', username = session['username'])

        member = Members.query.filter(Members.email == email).first()

        if member is None:
            flash("Error! Could not delete member because user with that email does not exist.")

        else:
            db.session.delete(member)
            db.session.commit()
            flash("Successfully Deleted Member")

    return render_template('addmember.html', username = session['username'])

@app.route('/members', methods=['GET','POST'])
def showmembers():
    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as Admin to access these functions")
        return render_template('login.html')

    memberlist = db.session.query(Members.username, Members.email).order_by(Members.username.asc(), Members.email.asc()).all()
    return render_template('showmembers.html', memberlist = memberlist, frametitle = "All Members", username = session['username'])

@app.route('/searchbook', methods=['POST'])
def searchbook():
    searchbookform = SearchBookForm(request.form)
    search = searchbookform.search.data

    if checkmember() == 'nomember':
        return userpage()

    else:
        booklist = Books.query.filter((Books.title.like('%' + search + '%')) | (Books.authors.like('%' + search + '%')) | (Books.genre.like('%' + search + '%')) | (Books.availability.like('%' + search + '%'))).order_by(Books.title.asc(), Books.authors.asc()).all()
        return render_template('showbooks.html', booklist = booklist, frametitle = "Search Books", username = session['username'])

@app.route('/issue_book', methods=['GET','POST'])
def issue_book():
    issuebookform = IssueBookForm(request.form)
    title = issuebookform.title.data
    email = issuebookform.email.data

    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as admin to access these functions")
        return render_template('login.html')

    if request.method == 'POST':

        if (title == '') | (email == ''):
            flash("Error! Missing Fields")
            booklist = db.engine.execute("select title, authors, genre from Books where availability='In Stock';")
            return render_template('issuebook.html', username = session['username'], booklist = booklist, ret = False) 
        
        member = Members.query.filter(Members.email == email).first()
        book = Books.query.filter(and_(Books.title == title, Books.availability == 'In Stock')).first()

        if (member is not None) and (book is not None):
            borrow = Borrows(title, email, date.today(), late = 0, fine = 0)
            db.engine.execute("update Books set availability='Out of Stock' where title='" + title + "';")
            db.session.add(borrow)
            db.session.commit()
            flash("Succesfully Issued Book!")

        else:
            flash("Error! Either the book is not available or the member does not exist.")
    
    booklist = db.engine.execute("select title, authors, genre from Books where availability='In Stock';")
    return render_template('issuebook.html', username = session['username'], booklist = booklist, ret = False)

@app.route('/add_book', methods = ['GET','POST'])
def add_book():
    addbookform = AddBookForm(request.form)
    title = addbookform.title.data
    authors = addbookform.authors.data
    genre = addbookform.genre.data
    availability = addbookform.availability.data

    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as Admin to access these functions")
        return render_template('login.html')

    if request.method == 'POST':

        if (title == '') | (authors == '') | (genre == '') | (availability == ''):
            flash("Error! Missing Fields")
            return render_template('addbook.html', username = session['username'])
        
        book = Books.query.filter(Books.title == title).first()

        if book is None:
            book = Books(title, authors, genre, availability)
            db.session.add(book)
            db.session.commit()
            flash("Successfully Added!")

        else:
            flash("Error! Book with the same title already exists.")

    return render_template('addbook.html', username = session['username'])

@app.route('/delete_book', methods=['GET','POST'])
def delete_book():
    deletebookform = DeleteBookForm(request.form)
    title = deletebookform.title.data

    if checkmember() == 'No Member':
        return userpage()

    elif checkmember() == 'Not Admin':
        flash("Error! Please Login as Admin to access these functions")
        return render_template('login.html')

    if request.method == 'POST':

        if (title == ''):
            flash("Error! Missing Fields")
            return render_template('addbook.html', username = session['username'])             

        book = Books.query.filter(Books.title == title).first()

        if book is None:
            flash("Error! Could not delete book because it does not exit.")

        else:
            db.session.delete(book)
            db.session.commit()
            flash("Successfully Deleted")

    return render_template('addbook.html', username = session['username'])


templates/addbook.html
{% extends "background.html" %}
{%block body2 %}
   <h1><div style = "Width:380px; border-radius:20px"> Add Book </h1>
<p>This form will add a book if it does not already exist </p>
    <hr>

<form action="{{url_for('app.add_book')}}" method="post">
    <input type="text" placeholder="Title" name="title">
    <input type="text" placeholder="Authors" name="authors">
    <input type="text" placeholder="Genre" name="genre">
    <input type="text" placeholder="Availability" name="availability">
    <input type="submit" value="Submit">
</form>

<br>
<br>

<h1><div style = "Width:380px; border-radius:20px"> Delete Book </h1>
<p>This form will delete an existing book</p>
    <hr>

<form action="{{url_for('app.delete_book')}}" method="post">
    <input type="text" placeholder="Bookname" name="title">
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/addmember.html
{% extends "background.html" %}
{%block body2 %}
   <h1><div style = "Width:380px; border-radius:10px">
       Add Member </h1>
    <p> This form will add a new member to the database.  </p>
    <hr>

<form action="{{url_for('app.add_member')}}" method="post">

    <input type="text" placeholder="Name" name="username">
    <input type="text" placeholder="Email" name="email">
    <input type="password" placeholder="Password" name="password">
    <input type="submit" value="Submit">
</form>

<br>
<br>

<h1><div style = "Width:380px; border-radius:10px">
    Delete Member </h1>
 <p> This form will delete an existing member from the database.  </p>
 <hr>

<form action="{{url_for('app.delete_member')}}" method="post">

    <input type="text" placeholder="Email" name="email">
    <input type="submit" value="Submit">
</form>

{% endblock %}

templates/background.html
{% extends "layout.html" %}
  
{%block body %}  

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{{ url_for('app.showbooks') }}" style="color:lightyellow">Catalogue</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="dropdown" >
          <a class="navbar-brand" href="#" class="dropdown-toggle" data-toggle="dropdown" > <span class="nav-label" style="color:lightyellow">Admin</span> <span class="caret" style="color: lightyellow"></span></a>
              <ul class="dropdown-menu navbar-inverse">
                  <li><a href="{{ url_for('app.issue_book') }}" style="color:lightyellow">Issue Book</a></li>
                  <li><a href="{{ url_for('app.return_book') }}" style="color:lightyellow">Return/Mark Late Book</a></li>
                  <li><a href="{{ url_for('app.add_book') }}" style="color:lightyellow">Manage Books</a></li>
                  <li><a href="{{ url_for('app.add_member') }}" style="color:lightyellow">Manage Members</a></li>
                  <li><a href="{{ url_for('app.showmembers') }}" style="color:lightyellow">Show All Members</a></li>
              </ul>
          </li>
          <li class="dropdown" >
            <a class="navbar-brand" href="#" class="dropdown-toggle" data-toggle="dropdown" > <span class="nav-label" style="color:lightyellow">Member</span> <span class="caret"></span></a>
                <ul class="dropdown-menu navbar-inverse">
                    <li><a href="{{ url_for('app.showmybooks') }}" style="color:lightyellow">My Issued Books</a></li>
                    <li><a href="{{ url_for('app.signout') }}" style="color:lightyellow">Sign Out</a></li>
                </ul>
          </li>
      </ul>
      <form class="navbar-form navbar-right" action="{{ url_for('app.searchbook') }}" method="POST">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for book" name="search">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </form>
      <h4 class="container-fluid" style="text-align: center; color:lightyellow">
       Welcome {{ username }}!
      </h4>
    </div>
  </nav>

<div style="border-radius: 1px; background-color: lightyellow; width: 85%; min-width:100px; padding:5px 5px 5px 5px;
margin:100px;" >
    {% block body2 %}
    {% endblock %}
</div>

{% endblock %}

templates/index.html
{% extends "layout.html" %}
{%block body %}

<nav class="navbar navbar-inverse">
   <div class="container-fluid">
     <h4 class="container-fluid" style="text-align: center; color:lightyellow">
      Welcome to our Library Management System!
     </h4>
   </div>
 </nav>

<div style=" border-radius: 20px; background-color: lightyellow; margin: auto;
width: 20%; padding:10px 25px 25px 25px; text-align:center; border: 5px solid #FFFF00;" >   <h1> Sign Up </h1>
    <hr>
   <form action= "{{ url_for('app.signup') }}" method="post" id="fsignup">
        <label style="width:70px; text-align:left"></label>
        <input type="text" placeholder="Name" name="username">
        <br>
        <label style="width:70px; text-align:left"></label>
        <input type="text" placeholder="Email" name="email">
        <br>
       <label style="width:70px; text-align:left"></label>
        <input type="password" placeholder="Password" name="password">
        <br>
       <label style="width:70px; text-align:left"></label>
        <input type="password" placeholder="Confirm Password" name="confirmpassword">
        <br>
       <br>

    </form>
    <input type="submit" name="Sign Up" form="fsignup" value="Submit">
    <a href="{{ url_for('app.userpage') }}"><button>Cancel</button></a>
</div>
{% endblock %}

templates/issuebook.html
{% extends "background.html" %}
{%block body2 %}
<h1><div style = "Width:220px; border-radius:10px">
{% if ret == True %}
   Return Book
{% else %}
   Issue Book
{% endif %}
    </h1>
    <hr>

    {% if ret == True %}
    <p>This form will return a book back to the database. </p>
    <form action= "{{url_for('app.return_book')}}" method="post">
        <input type="text" placeholder="Title" name="title">
        <input type="text" placeholder="Member email" name="email">
    {% else %}
    <p> This form will issue a book to a user.  </p>
    <form action= "{{url_for('app.issue_book')}}" method="post">
        <input type="text" placeholder="Title" name="title">
        <input type="text" placeholder="Member email" name="email">
    {% endif %}
    <input type="submit" value="Submit">
</form>
{% if ret == True %}
<h3>Issued Books</h3>
{% else %}
<h3>Available Books</h3>
{% endif %}
<hr>

<table class = "table table-bordered">
    <tr>
        <th style="width:400px">Title</th>
        {% if ret == False %}
        <th style="width:400px">Authors</th>
        <th style="width:400px">Genre</th>
        {% else %}
        <th style="width:400px">Email</th>
        <th style="width:400px">Issued Date</th>
        <th style="width:400px">Mark Book Late</th>
        {% endif %}
    </tr>

    {% for book in booklist %}
    <tr>
        {% if ret == True %}
        <td  style="width:400px">{{ book.title }}</td>
        <td  style="width:400px">{{ book.email }}</td>
        <td  style="width:400px">{{ book.issuedt }}</td>
        <td  style="width:400px">
            <form action="{{url_for('app.issue_late')}}" method="post">
                <button type="submit" >Mark Late {{ book.title }}</button>
                <input type="hidden" value = "{{book.title}}" name = "title">
            </form>
        </td>
        {% else %}
        <td  style="width:400px">{{ book.title }}</td>
        <td  style="width:400px">{{ book.authors }}</td>
        <td  style="width:400px">{{ book.genre }}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Library</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>

<div class="container" >
</div>

    {% for message in get_flashed_messages() %}

<div class="container-fluid" style="border-radius: 20px;background-color:lightyellow; color: red;
width: 25%; min-width:300px;">

    {{ message }}

</div>

    {% endfor %}


<div class="container-fluid">
    {% block body %}
    {% endblock %}
</div>

</body>
</html>

templates/login.html
{% extends "layout.html" %}
{%block body %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <h4 class="container-fluid" style="text-align: center; color:lightyellow">
       Welcome to our Library Management System!
      </h4>
    </div>
  </nav>

<div style=" border-radius: 20px; background-color: lightyellow; margin: auto;
width: 20%; padding:10px 25px 25px 25px; text-align:center; border: 5px solid #FFFF00;" >
   <h1 style = "text-align:center;">Login</h1>
    <hr>
   <form action= "{{ url_for('app.userpage') }}" id="flogin" method="post">
        <label style="width:100px"></label>
        <input type="text" placeholder="Email" name="email">
        <br>
        <label style="width:100px"></label>
        <input type="password" placeholder="Password" name="password">
        <br>
       <br>
   </form>
    <button type="submit" form=flogin name="submit"> Login </button>
    <a href="{{ url_for('app.signup') }}"><button> Sign Up </button></a>   
</div>

{% endblock %}

templates/showbooks.html
{% extends "background.html" %}
{%block body2 %}
   <h1>
       {% if frametitle == "Your Books" %}
       My Issued Books 
       {% elif frametitle == "Search Books" %}
       Search Book Results 
       {% else %}
       Book Catalogue
       {% endif %}
   </h1>
    <hr>

{% if frametitle == "Your Books" %}
<div>Your Fines: ${{ cost }}</div>
{% endif %}

<table class = "table table-bordered">
    <tr>
        <th style="width:800px">Title</th>
        {% if frametitle == "Your Books" %}
        <th style="width:800px">Issued Date</th>
        {% else %}
        <th style="width:800px">Authors<br></th>
        <th style="width:500px">Genre<br></th>
        <th style="width:80px">Availability<br></th>
        {% endif %}
    </tr>
    {% for book in booklist %}
    <tr>
        <td  style="width:800px">{{ book.title }}<br></td>
        {% if frametitle == "Your Books" %}
        <td  style="width:800px">{{ book.issuedt }}<br></td>
        {% else %}
        <td  style="width:800px">{{ book.authors }}<br></td>
        <td  style="width:500px">{{ book.genre }}<br></td>
        <td  style="width:90px">{{ book.availability }}<br></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

templates/showmembers.html
{% extends "background.html" %}
{%block body2 %}
   <h1><div style = "Width:280px; border-radius:10px"> Members List </h1>
    <hr>
<table class = "table table-bordered">
    <tr>
        <th style="width:400px">Name</th>
        <th style="width:400px">Email</th>
    </tr>
    {% for member in memberlist %}
    <tr>
        <td  style="width:400px">{{ member.username }}</td>
        <td  style="width:400px">{{ member.email }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}